import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ClerkProvider } from '@clerk/nextjs'
import Downfooter from "./components/Downfooter";
import ScrollToTopButton from "./components/ScrollToTopButton";
import Chatbot from "./components/Chatbot";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = { 
  title: "Codingcheff",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      
      <body className={inter.className}><Navbar/>{children}<Downfooter/><ScrollToTopButton/><Chatbot/></body>
    </html>
    </ClerkProvider>
  );
}

